### ISSUE TITLE
关于tex文档和pdf互相定位的问题( Questions about tex documents and pdf positioning each other)

### ISSUE THREAD

**Issue by YLXDXX** [mrpiggi/svg#14]
我用的编辑软件是texstudio，但是在插入svg图片处，不能够使用ctr+鼠标右键在tex文档和pdf之间相互定位。

The editing software I use is texstudio, but when I insert the svg image, I can't use the ctr + right mouse button to locate each other between the tex document and the pdf.

(frome translate.google.com)

**Comment by mrpiggi** [comment]
Well, this is not related to package `svg` but to TeXstudio itself. Maybe you could open a feature request right here: https://sourceforge.net/p/texstudio/feature-requests/
