### ISSUE TITLE
Package Warning after Update

### ISSUE THREAD

**Issue by Goreak** [mrpiggi/svg#18]
I updated MikTex today. Now I get the warning for every \ includesvg instruction:

Package scrbase Warning: Usage of deprecated command `\ ifstr '.
(scrbase) The command has been renamed because of a
(scrbase) recommendation of The LaTeX Project Team.
(scrbase) Please replace `\ ifstr 'by` \ Ifstr' on input line xx.

Is there any way to fix this error?

I'm using TeXnicCenter with Komascript scrbook.

**Comment by komascript** [comment]
I would suggest to add something like the

```latex
\providecommand*\Ifstr{\ifstr}
```

to `svg.sty` after loading `scrlfile` as recommnended on https://komascript.de/faq_deprecatedif and then use `\Ifstr` inside `svg.sty`. With this `svg` would be compatible with old and new KOMA-Script releases.

**Comment by Goreak** [comment]
Unfortunately, that doesn't really work. I don't use the scrbase package at all. The message comes with every svg graphic that I include in my script. The instructions do not change the amount of warnings either.

**Comment by komascript** [comment]
@Goreak My comment was not a suggestion to user but to mrpiggi as package author. And he would have to abstract the suggestion to other `\if…`/\`\If…` from `scrbase`, i.e., `\ifnumber`/`\Ifnumber`, `\ifisdimension`/`\Ifisdimension`, in `svg.sty`.

**Comment by mrpiggi** [comment]
Thanks to @komascript. As the current develop branch is meant for version v2.03 I am going to prepare a hotfix release until the end of this week. Please be patient.
