### ISSUE TITLE
Unable to run on Win 10 + MikTeX after update to v2.02f

### ISSUE THREAD

**Issue by tpsales** [mrpiggi/svg#24]
Hello!

First and foremost, thank you very much for maintaining the svg package.

Before the latest update (v2.02f), the package worked flawlessly for me.

Now, after performing the referred update, when I try to compile a latex file using lualatex (with shell-escape enabled), I am faced with the message bellow, during compilation:

> '\\\\?\D:\Thiago\Documents\AULA-07' CMD.EXE was started with the above path as the current directory. UNC paths are not supported. Defaulting to Windows Directory. 

I am almost certain that the issue is not related with the latex file I am trying to compile, neither with my system setup. Before the update, I had compiled the same exact file without any issues.

I have tried debugging the code to pinpoint where the issue is, but to no avail. (I admit I have almost no experience with lua / latex scripting.)

If you think I can help debugging the issue, please give me instructions.

Thank you!

**Comment by tpsales** [comment]
Please ignore me.

I am just a terrible debugger. :(

The issue is related to another package...

Sorry for any trouble!

And thank you once again for maintaining the package!

**Comment by mrpiggi** [comment]
You are welcome ;)
