### ISSUE TITLE
Default size

### ISSUE THREAD

**Issue by lberrada** [mrpiggi/svg#26]
Hi, many thanks for the great package. Despite spending time reading the doc, I haven't been able to figure out the answer to the following question:

Given an SVG input file with specified height and width in pixels and the default `scale=1`, what are the dimensions of the resulting compiled image (in units understood by latex)? I would have expected `includesvg` to use a DPI value that translates the size in pixels to a size in cm/in/pt, but I haven't been able to find this (in my code, changing the value of the `inkscapedpi` option seems to have no effect on the resulting size of the image).

**Comment by mrpiggi** [comment]
Maybe there's been a misunderstanding with you. ***Inkscape*** usually creates vector graphics in PDF format, which can be scaled as desired. Specifying the parameters `width/height/scale` allows scaling the graphic to the desired size within the document. These parameters are passed internally to the `\includegraphics` command from package `graphicx`, which is used to include the exported PDF file.

The option `inkscapedpi` is only meaningfull, if either the export format is PNG or the SVG file contains filtered objects, which should be rasterized.

For the translation between pixels and LaTeX units see: https://tex.stackexchange.com/a/41371/38481

**Comment by lberrada** [comment]
This is very helpful, many thanks for clarifying!
