### ISSUE TITLE
Doesn't work with markdown package

### ISSUE THREAD

**Issue by hacker-DOM** [mrpiggi/svg#28]
Input:
```
\documentclass{article}

\usepackage{markdown}
\usepackage{svg}
\begin{document}
a
\end{document}
```

Expected output: `a`

Received: gibberish.

Also see same issue on [markdown](https://github.com/Witiko/markdown/issues/66).

**Comment by hacker-DOM** [comment]
Enountered on Overleaf with poth Lualatex and pdflatex.

**Comment by mrpiggi** [comment]
The problem can be further reduced to the package `pgfrcs`. I will have a look at this.

**Comment by mrpiggi** [comment]
And strips down to this issue: https://github.com/ho-tex/transparent/issues/3

Actually I had included a fix for the package `transparent` in the assumption that the problem will be solved with the next release. But this was not the case. This should work:
```latex
\documentclass{article}
\usepackage{markdown}
\usepackage{svg}
\usepackage{pgfsys}
\begin{document}
a
\end{document}
```
Alternatively you can disable the package with option `\usepackage[usetransparent=false]{svg}`.

**Comment by mrpiggi** [comment]
Please keep in mind, that Overleaf currently uses TeX Live 2019. This fix won't be available with Overleaf until it---and of course your project as well---is updated to TeX Live 2020.
