### ISSUE TITLE
unknown option -z

### ISSUE THREAD

**Issue by schorschie** [mrpiggi/svg#34]
I had to change `svg.sty` to get it to work:

```latex
\newcommand*\svg@ink@cmd[2]{%
  \svg@ink@exe\space--without-gui\space\svg@ink@area\space%
  \ifx\svg@ink@dpi\relax\else--export-dpi=\svg@ink@dpi\space\fi%
  \if@svg@ink@latex--export-latex\space\fi%
  \svg@ink@opt\space%
  "#1.svg"\space%
  --export-filename="#2.\svg@ink@format"\space%
}
````
but most likely I'm on an outdated version, can't check that right now.

**Comment by mrpiggi** [comment]
Please update your distribution. This problem has already been discussed (#20/#22/#25) and was fixed long time ago with `v2.02f` cc773677c2e79dd7fa2d3c60104f1d3c788300c6
