### ISSUE TITLE
Inkscape depracted options

### ISSUE THREAD

**Issue by leomayer** [mrpiggi/svg#38]
With `Inkscape 1.0.1 (3bc2e813f5, 2020-09-07)` the options 

- `--without-gui`
- `--file`
- `export-pdf`

become depracted. See as well on [TexExchange](https://tex.stackexchange.com/a/542962/48642)

**Comment by mrpiggi** [comment]
This was already adapted with `v2.02f` so please update bundle `svg` via your LaTeX distribution.

**Comment by leomayer** [comment]
Yes and no. When I download the sources from CTAN 2.02k than I see

```
\newcommand*\svg@ink@cmd[2]{%
  \svg@ink@exe\space"#1.\svg@file@ext"\space\svg@ink@area\space%
  \ifx\svg@ink@dpi\relax\else--export-dpi=\svg@ink@dpi\space\fi%
  \if@svg@ink@latex--export-latex\space\fi%
  \ifx\svg@ink@opt\@empty\else\svg@ink@opt\space\fi%
  \ifcase\svg@ink@ver\relax% 0.x detected
    --without-gui\space%
    --export-\svg@ink@format="#2.\svg@ink@format"%
  \else% 1.x or nothing detected
    --export-filename="#2.\svg@ink@format"%
  \fi%
}
```

which still leaves the `withouth-gui` option. For the other options I agree.

**Comment by mrpiggi** [comment]
This is only invoked, when Inkscape version 0.x is detected

**Comment by leomayer** [comment]
ahhh - ok than close this ticket .
