### ISSUE TITLE
Name conflicts when not using a single image folder

### ISSUE THREAD

**Issue by dafred94** [mrpiggi/svg#39]
My project folder looks like this:

```
.
├── mydoc.tex
├── topic 1
│   ├── im.svg
│   └── text.tex
└── topic 2
    ├── im.svg
    └── text.tex
```

In `mydoc.tex`, I input `topic 1/text.tex` and `topic 2/text.tex`. In the former file, I use `includesvg{topic 1/im}`, in the latter file I use `includesvg{topic 2/im}`.

Of course in the `svg-inkscape/` directory that is created on the same level as `mydoc.tex`, the file names are now ambiguous and one of the images can be seen a second time instead of the second image in the rendered document `mydoc.pdf`.

Is there a way to instruct your extension to be able to differentiate between the files by including information about the relative path between images and the root tex document?
I believe that option `inkscapename` should be the way to go but I couldn't figure out how to use it...

Thanks in advance!

**Comment by mrpiggi** [comment]
This is an already known problem (#11) and unfortunately I haven't found the time to fix it properly yet. With `inkscapepath=svgsubdir` the created files are stored in the respective subfolder.
