### ISSUE TITLE
Rendering twice removes the output

### ISSUE THREAD

**Issue by MrSmallAmount** [mrpiggi/svg#44]
If I render the following .tex-File everything works as expected. Rendering twice results in an empty PDF document.

I am on TeXLive 2022, Ubuntu 22.04. My drawing.svg is located in my working directory.

```
\documentclass[11pt,a4paper]{article}
\usepackage{svg}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{document}
Hello \\
\begin{figure}[h]
\includesvg{drawing.svg}
\end{figure}
\end{document}
```

The drawing.svg was created with Inkscape and contains the following.

![drawing](https://user-images.githubusercontent.com/105462358/173831712-28dc5cd0-ffd1-4f27-ab04-bb6a86eed771.svg)

**Comment by mrpiggi** [comment]
Although not reflected by Inkscape when just simply opening your file (maybe worth a bug report ), the text is set with opacity=0. As setting transparency in LaTeX just kicks in in the second run, you get the described behavior.
