### ISSUE TITLE
`svg` package takes the bounding box of the original SVG as opposed to the bounding box resulting from the text conversion

### ISSUE THREAD

**Issue by awa5114** [mrpiggi/svg#49]
The following

```
\documentclass{standalone}

\usepackage{svg}
\usepackage{relsize}
\usepackage{amsmath}

\begin{document}
    \includesvg[inkscapelatex=false,pretex=\relsize{1.3}]{idea.svg}
\end{document}
```

results in 

![image](https://user-images.githubusercontent.com/24267968/223317873-993f0927-323f-444a-8c74-ce931b5e9b06.png)

If I set `inkscapelatex=true` I get the following:

![image](https://user-images.githubusercontent.com/24267968/223317973-7c4b8b14-2251-4008-910d-c7a6e4ff5323.png)

Notice that:
- There is significant whitespace to the left of $\text{cumulative} = \int{\text{Rate}} \, dt$
- The integral symbol is cut off

This indicates that `svg` package takes the bounding box of the original SVG as opposed to the bounding box resulting from converting all the text into math.

**Comment by mrpiggi** [comment]
@amine-aboufirass If you are cross-posting, then please at least make it clear by providing the relevant link: https://tex.stackexchange.com/questions/678559

**Comment by mrpiggi** [comment]
no feedback, neither here nor at SE.com
