### ISSUE TITLE
Issue using svg together with tikzscale

### ISSUE THREAD

**Issue by namezulang** [mrpiggi/svg#5]
Since the latest release, a problem occured using the svg package together with the tikzscale package.

MWE:
```latex
\documentclass{scrreprt}

\usepackage{tikz}
\usepackage{tikzscale}

\usepackage[]{svg}                                 
\svgpath{figures/}		


\begin{document}

\begin{figure}[tb]
	\centering
	\includesvg[width=0.7\linewidth]{figures/test}
\end{figure}

\end{document} 
```

Compiling the above code fails with following error message:
```
! LaTeX Error: File `{./svg-inkscape/test_svg-tex}.pdf' not found.
```
However, the files 'test_svg-tex.pdf' and 'test_svg-tex.pdf_tex' in the 'svg-inkscape' folder are correctly generated.

When commenting out the line '\usepackage{tikzscale}', the error vanishes and the document compiles correctly. The test system used pdfLaTex on Windows and Inkscape 0.92.3.

**Comment by mrpiggi** [comment]
Well, actually it's an error caused by package **tikzscale** as it changes the definition of `\includegraphics` globally. Nevertheless, I'm going to provide a bugfix release.
