### ISSUE TITLE
 Text Reference Displays Section Number Instead of Figure Number with \ref

### ISSUE THREAD

**Issue by vyctor922** [mrpiggi/svg#58]
I'm currently using Overleaf to edit LaTeX documents and incorporating vector images into the document using the SVG package.

While attempting to reference an image in the text using \ref, I noticed that the link is functional. However, the text displayed in the reference is the section number, not the figure number.

It's likely a straightforward issue, but I'm just an amateur when it comes to LaTeX packages.
<br>

Thank you for your attention.
<br>
<br>

~Below are images of the attempt

<p align="center">
<img src=https://github.com/mrpiggi/svg/assets/49332954/cc7de7b5-64d8-43ce-b4ef-0a98f7056f5a>
</p>

![image](https://github.com/mrpiggi/svg/assets/49332954/acbe480e-9556-43d6-96f8-91b2c76230ee)

**Comment by mrpiggi** [comment]
This has nothing to do with this package but with references in general.

Just for the record, the number you are mentioning is in the picture itself and therefor can not be referenced dynamically at all.
