### ISSUE TITLE
runsystem information not being output to log

### ISSUE THREAD

**Issue by bluebaroncanada** [mrpiggi/svg#9]
In the docs and error message it says that I should be able to view the command for inkscape, but it's not being output to any log.

**Comment by mrpiggi** [comment]
Well, it actually writes to corresponding log file. If you create a latex document `test.tex` (assuming Tex Live 2019 on Windows)
```tex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{svg}
\begin{document}
\svgpath{{C:/texlive/2019/texmf-dist/doc/latex/svg/}}% path to svg-example.svg
\begin{figure}
\centering
\includesvg[inkscape=force]{svg-example}
\end{figure}
\end{document}
```
and run `pdflatex --shell-escape test.tex` then there is an information about the execution of inkscape within `test.log`
```
Package svg Info: Calling Inkscape on input line 14.
runsystem(inkscape -z -D --export-latex  --file="C:/texlive/2019/texmf-dist/doc
/latex/svg/svg-example.svg" --export-pdf="svg-example_svg-tex.pdf" )...executed
```

**Comment by bluebaroncanada** [comment]
Yes.  That definitely is not occurring:
https://tex.stackexchange.com/questions/284701/svg-package-failing-to-find-svg-files

**Comment by mrpiggi** [comment]
So it looks to me, that's not a direct with package svg. It seems, that you already got a useful answer at stackoverflow not to use `texify`. Incidentally, you could have noticed that yourself, if you had used `pdflatex` as I suggested in my last answer.

**Comment by mrpiggi** [comment]
This issue actually lead to this one: https://github.com/latex3/latex2e/issues/195
